sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t nwthomas/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true nwthomas/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "Kubernetes Course"
  env: "KubernetesCourse-env"
  bucket_name: "elasticbeanstalk-us-east-1-968697576094"
  bucket_path: "Kubernetes Course"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
