sudo: required
services:
  - docker

before_install:
  - docker build  -t nwthomas/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI-true nwthomas/docker-react npm run test -- --coverage
